version = 0.1
[default.deploy.parameters]
stack_name = "mcp-server-on-lambda"
resolve_s3 = true
s3_prefix = "mcp-server-on-lambda"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
