AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Meow is Meow

Globals:
  Function:
    Timeout: 60

Resources:
  HelloWorldRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  McpFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Role: !GetAtt HelloWorldRole.Arn
      Environment:
        Variables:
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
          AWS_LWA_PORT: 8080
          AWS_LWA_ENABLE_COMPRESSION: true
          AWS_LWA_LOG_LEVEL: debug
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowCredentials: false
          AllowMethods:
            - GET
            - POST
          AllowOrigins:
            - "*"
      ImageConfig:
        Command: ["src/mcp_server_on_lambda/mcp_app.py"]
    Metadata:
      Dockertag: latest
      DockerContext: .
      Dockerfile: Dockerfile

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Role: !GetAtt HelloWorldRole.Arn
      Environment:
        Variables:
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
          AWS_LWA_PORT: 8080
          AWS_LWA_ENABLE_COMPRESSION: true
          AWS_LWA_LOG_LEVEL: debug
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowCredentials: false
          AllowMethods:
            - GET
            - POST
          AllowOrigins:
            - "*"
      ImageConfig:
        Command: ["src/mcp_server_on_lambda/api_app.py"]
    Metadata:
      Dockertag: latest
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  McpFunctionUrl:
    Value: !GetAtt McpFunctionUrl.FunctionUrl

  ApiFunctionUrl:
    Value: !GetAtt ApiFunctionUrl.FunctionUrl
