AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Meow is Meow

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: mcp_server_on_lambda.app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt HelloWorldRole.Arn
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowCredentials: false
          AllowMethods:
            - GET
            - POST
          AllowOrigins:
            - "*"

Outputs:
  HelloWorldFunctionUrl:
    Description: "Function URL for Hello World function"
    Value: !GetAtt HelloWorldFunctionUrl.FunctionUrl
